
name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::024848454001:role/github-actions-drabovski"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "drabovski-sa-east-1-terraform"
      aws-lock-dynamodb-table: "drabovski-sa-east-1-terraform"
